# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - devopsprojectapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://devopsprojectb.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e5a95a3022dc412798b488ba72da1cee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_560bc878a0e7461281c13194fd91081d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: devopsprojectb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5a95a3022dc412798b488ba72da1cee }}/calculatorapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devopsprojectapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2b01b4dba6f4a9fb031d34b7cc754c8 }}
        images: 'devopsprojectb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5a95a3022dc412798b488ba72da1cee }}/calculatorapp:${{ github.sha }}'